spring:
  application:
    name: spring-client

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics      # default: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces    # default: http://localhost:4318/v1/traces

# traceID and spanId are predefined MDC keys - we want the logs to include them.
# This configuration only works with standard Logback configuration. Not in our case.
#logging:
#  pattern:
#   level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"